basePath: '{{.BasePath}}'
definitions:
  model.CreateProduct:
    properties:
      description:
        description: Mô tả sản phẩm
        type: string
      image:
        description: Ảnh sản phẩm
        type: string
      manufacture:
        description: Hãng sản xuất
        type: string
      name:
        description: Tên hiển thị
        type: string
      price:
        description: Giá sản phẩm
        type: integer
      quantity:
        description: Số lượng
        type: integer
    type: object
  model.CreateUser:
    properties:
      password:
        description: Mật khẩu phải có tối thiểu 8 ký tự
        type: string
      username:
        description: Tên hiển thị
        type: string
    type: object
  model.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /auth/create-product:
    post:
      description: Tạo Product
      parameters:
      - description: Thông tin tạo sản phẩm
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateProduct'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /auth/create-user:
    post:
      description: Register User
      parameters:
      - description: Thông tin Register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateUser'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /auth/delete-product/{id}:
    delete:
      description: Xóa Product theo ID
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /auth/get-product/{id}:
    get:
      description: Lấy thông tin Product theo ID
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /auth/get-products:
    get:
      description: Lấy danh sách Products
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /auth/get-users:
    get:
      description: Lấy danh sách User
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /auth/login-user/{id}:
    get:
      description: Login User theo ID
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /auth/update-product/{id}:
    put:
      description: Cập nhật Product theo ID
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
swagger: "2.0"
