basePath: '{{.BasePath}}'
definitions:
  model.CreateProduct:
    properties:
      description:
        description: Mô tả sản phẩm
        type: string
      image:
        description: Ảnh sản phẩm
        type: string
      manufacturer:
        description: Hãng sản xuất
        type: string
      name:
        description: Tên hiển thị
        type: string
      price:
        description: Giá sản phẩm
        type: number
      quantity:
        description: Số lượng
        type: integer
    type: object
  model.CreateUser:
    properties:
      password:
        description: Mật khẩu phải có tối thiểu 8 ký tự
        type: string
      username:
        description: Tên hiển thị
        type: string
    type: object
  model.GetProductById:
    properties:
      description:
        description: Mô tả sản phẩm
        type: string
      id:
        description: Mã User (chuỗi ngẫu nhiên duy nhất)
        type: string
      image:
        description: Ảnh sản phẩm
        type: string
      manufacturer:
        description: Hãng sản xuất
        type: string
      name:
        description: Tên hiển thị
        type: string
      price:
        description: Giá sản phẩm
        type: number
      quantity:
        description: Số lượng
        type: integer
    type: object
  model.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  model.UpdateProductById:
    properties:
      description:
        description: Mô tả sản phẩm
        type: string
      id:
        description: Mã User (chuỗi ngẫu nhiên duy nhất)
        type: string
      image:
        description: Ảnh sản phẩm
        type: string
      manufacturer:
        description: Hãng sản xuất
        type: string
      name:
        description: Tên hiển thị
        type: string
      price:
        description: Giá sản phẩm
        type: number
      quantity:
        description: Số lượng
        type: integer
    type: object
  model.UserLogIn:
    properties:
      password:
        description: Mật khẩu phải có tối thiểu 8 ký tự
        type: string
      username:
        description: Tên hiển thị
        type: string
    type: object
host: '{{.Host}}'
info:
  contact: {}
  description: '{{.Description}}'
  license: {}
  title: '{{.Title}}'
  version: '{{.Version}}'
paths:
  /shop/create-product:
    post:
      description: Tạo Product
      parameters:
      - description: Thông tin tạo sản phẩm
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateProduct'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /shop/create-user:
    post:
      description: Register User
      parameters:
      - description: Thông tin Register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateUser'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /shop/delete-product/{id}:
    delete:
      description: Xóa Product theo ID
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /shop/get-product/{id}:
    get:
      description: Lấy thông tin Product theo ID
      parameters:
      - description: Sản phẩm
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.GetProductById'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /shop/get-products:
    get:
      description: Lấy danh sách Products
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /shop/get-users:
    get:
      description: Lấy danh sách User
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /shop/login-user:
    post:
      description: Login User theo username
      parameters:
      - description: Đăng nhập
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserLogIn'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
  /shop/update-product/{id}:
    put:
      description: Cập nhật Product theo ID
      parameters:
      - description: Thông tin sản phẩm
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.UpdateProductById'
          type: object
      responses:
        "200":
          description: OK
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.HTTPError'
            type: object
      tags:
      - admin
swagger: "2.0"
